Proyecto_DSW1/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_DSW1.Models;
using Proyecto_DSW1.Permisos;

namespace Proyecto_DSW1.Controllers
{
    [ValidarSesion]
    public class ClienteController : Controller
    {
        private BD_DSW1Entities db = new BD_DSW1Entities();
        public ActionResult Index()
        {
            var cliente = db.Cliente.Include(c => c.Distrito);
            return View(cliente.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        public ActionResult Create()
        {
            ViewBag.idDistrito = new SelectList(db.Distrito, "idDistrito", "nom_dis");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCliente,idDistrito,dni_clie,nom_cli,ape_cli,mail_cli,tel_cli")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idDistrito = new SelectList(db.Distrito, "idDistrito", "nom_dis", cliente.idDistrito);
            return View(cliente);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDistrito = new SelectList(db.Distrito, "idDistrito", "nom_dis", cliente.idDistrito);
            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCliente,idDistrito,dni_clie,nom_cli,ape_cli,mail_cli,tel_cli")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDistrito = new SelectList(db.Distrito, "idDistrito", "nom_dis", cliente.idDistrito);
            return View(cliente);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_DSW1/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Data.Entity;
using System.Web.Mvc;

using Proyecto_DSW1.Models;
using System.Web.Helpers;
//using System.Data.Entity;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using Proyecto_DSW1.Permisos;

namespace Proyecto_DSW1.Controllers
{
    [ValidarSesion]
    public class ProductoController : Controller
    {
        // GET: Producto
        BD_DSW1Entities db = new BD_DSW1Entities();
        public ActionResult Index()
        {
            return View(db.Producto.ToList());
        }

        public ActionResult IndexCarrito()
        {
            return View(db.Producto.ToList().OrderBy(x => x.des_prod));
        }

        /*
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/fotos"), filename);
                file.SaveAs(path);
            }
            return RedirectToAction("Index");
        }
        */
        public ActionResult Create()
        {
            ViewBag.categorias = new SelectList(db.Categoria, "idCategoria", "nom_cat");
            return View(new Producto());
        }
        [HttpPost]
        public ActionResult Create(Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }               
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Categorias = new SelectList(db.Categoria, "idCategoria", "nom_cat", producto.idCategoria);
            return View(producto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }

        public ActionResult Delete(FormCollection fcNotUsed, int id = 0)
        {
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Proyecto_DSW1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Proyecto DSW</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("STORE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Productos", "Index", "Home")</li>
                    <li>@Html.ActionLink("Consulta", "CategoriaListar", "Consulta")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mantenimientos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Productos</li>
                            <li>@Html.ActionLink("Productos", "Index", "Producto")</li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Clientes</li>
                            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Cerrar Sesión", "Login", "Login")</li>
                </ul>               
            </div><!--/.nav-collapse -->
        </div>
    </nav>





    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

<footer>
    @*style="background-color: rgb(33 33 33 / 0.65)*@
    <div class="footer-top">
        <div class="container">
            <div class="row flex-flow">
                <div class="col-sm-12 col-md-4 footer-sidebar">
                    <div class="widget contact-info">
                        <h3 class="widget-title">Contáctanos</h3>
                        <div class="content">
                            <p class="address"> Ubicacion - Independencia</p>
                            <p class="address">atencionalcliente@commerce.pe</p>
                            <p class="phone"><i class="fa fa-phone"></i> (01) 200-0333</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4 footer-sidebar">
                    <div class="widget our-service">
                        <h3 class="widget-title">SERVICIO AL CLIENTE</h3>
                        <div class="content">
                            <ul>
                                <li><a class="a" href="">Términos & Condiciones</a></li>
                                <li><a class="a" href="">Libro de reclamaciones</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4 footer-sidebar">
                    <div class="widget our-service">
                        <h3 class="widget-title">INFORMACIÓN</h3>
                        <div class="content">
                            <ul>
                                <li><a class="a" href="">Tarjeta virtual</a></li>
                                <li><a class="a" href="">¿Cómo funciona?</a></li>
                                <li><a class="a" href="">Preguntas frecuentes</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p class="text-center">STORE Todos los derechos reservados</p>
        </div>
    </div>
</footer>
</html>
<style>
    body{
        margin:0;
        display:grid;
        min-height:100vh;
        grid-template-rows:auto 1fr auto;
        padding-bottom:0
    }
    footer {
        background-color: #B3B6B7;
        padding:1em 0 0 0;
        margin-top:auto;
        padding-top:0
    }
    p {
        font-size: 10px;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif
    }
    h3 {
        font-size: 15px;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
    }
    .a {
        font-size: 10px;
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif

    }
    a {
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif
    }
</style>