Proyecto_DSW1/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DSW1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }
    
        public int idProducto { get; set; }
        public Nullable<int> idCategoria { get; set; }
        [Required(ErrorMessage = "Ingrese nombre producto")]
        public string nom_prod { get; set; }

        [Required(ErrorMessage = "Ingrese precio")]
        public double pre_prod { get; set; }
        [Required(ErrorMessage = "Ingrese stock")]
        public int sto_prod { get; set; }
        [Required(ErrorMessage = "Ingrese Imagen")]
        public string img_prod { get; set; }
        [Required(ErrorMessage = "Ingrese descripcion de producto")]
        public string des_prod { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
    }
}

Proyecto_DSW1/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_DSW1.Models;
using Proyecto_DSW1.Permisos;

namespace Proyecto_DSW1.Controllers
{
    [ValidarSesion]
    public class CarritoController : Controller
    {
        // GET: Carrito
        BD_DSW1Entities db = new BD_DSW1Entities();

        private int getIndex( int id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for(int i = 0;i<compras.Count; i++)
            {
                if (compras[i].Producto.idProducto == id)
                    return i;
            }
            return -1;
        }

        public ActionResult AgregarCarrito(int id)
        {
            if(Session["carrito"] == null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                compras.Add(new CarritoItem(db.Producto.Find(id), 1));
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1)
                    compras.Add(new CarritoItem(db.Producto.Find(id), 1));
                else
                    compras[IndexExistente].Cantidad ++;
                Session["carrito"] = compras;
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            compras.RemoveAt(getIndex(id));
            return View("AgregarCarrito");
        }

        public ActionResult FinalizarCompra()
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            if(compras != null && compras.Count > 0)
            {
                Pedido nuevaVenta = new Pedido();
                nuevaVenta.fech_pedido = DateTime.Now;
                nuevaVenta.Subtotal = compras.Sum(x => x.Producto.pre_prod * x.Cantidad);
                nuevaVenta.Iva = nuevaVenta.Subtotal * 0.18;
                nuevaVenta.Total = nuevaVenta.Subtotal + nuevaVenta.Iva;

                nuevaVenta.PedidoDetalle = (from Producto in compras
                                         select new PedidoDetalle
                                         {
                                             idProducto = Producto.Producto.idProducto ,
                                             Cantidad = Producto.Cantidad,
                                             Total = Producto.Cantidad * Producto.Producto.pre_prod
                                         }).ToList();
                db.Pedido.Add(nuevaVenta);
                db.SaveChanges();
                Session["carrito"] = new List<CarritoItem>();            
            }
            return View();
        }


        public ActionResult Index()
        {
            return View();
        }
    }
}

Proyecto_DSW1/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Data.Entity;
using System.Web.Mvc;

using Proyecto_DSW1.Models;
using System.Web.Helpers;
//using System.Data.Entity;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using Proyecto_DSW1.Permisos;

namespace Proyecto_DSW1.Controllers
{
    [ValidarSesion]
    public class ProductoController : Controller
    {
        // GET: Producto
        BD_DSW1Entities db = new BD_DSW1Entities();
        public ActionResult Index()
        {
            return View(db.Producto.ToList());
        }

        public ActionResult IndexCarrito()
        {
            return View(db.Producto.ToList().OrderBy(x => x.des_prod));
        }

        /*
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/fotos"), filename);
                file.SaveAs(path);
            }
            return RedirectToAction("Index");
        }
        */
        public ActionResult Create()
        {
            ViewBag.categorias = new SelectList(db.Categoria, "idCategoria", "nom_cat");
            return View(new Producto());
        }
        [HttpPost]
        public ActionResult Create(Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }               
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Categorias = new SelectList(db.Categoria, "idCategoria", "nom_cat", producto.idCategoria);
            return View(producto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }

        public ActionResult Delete(FormCollection fcNotUsed, int id = 0)
        {
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Proyecto_DSW1/Views/Producto/Create.cshtml
@model Proyecto_DSW1.Models.Producto

@{
    ViewBag.Title = "Create";
}
<body style="background-color: #42413D">

    <h2 class="text-center" style="color:lightslategray ;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">AGREGAR NUEVO PRODUCTO</h2>

    @*@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))*@
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Datos de Producto</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Categoria</label>
                <div class="col-md-10">
                    @Html.DropDownList("idCategoria", (SelectList)ViewBag.categorias, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Producto</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nom_prod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nom_prod, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Precio</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.pre_prod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.pre_prod, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Stock</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.sto_prod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.sto_prod, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Imagen</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img_prod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.img_prod, "", new { @class = "text-danger" })
                    @*<input name="img_prod" type="file" />*@
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" style="color:white">Descripcion</label>
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.des_prod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.des_prod, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Agregar Producto" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("REGRESAR", "Index", null, new { @class = "btn btn-warning" })
    </div>
    <br />
</body>
<style>
    h4{
        color:white
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto_DSW1/Views/Producto/Edit.cshtml
@model Proyecto_DSW1.Models.Producto

@{
    ViewBag.Title = "Edit";
}
<body  style="background-color: #42413D">

<h2 class="text-center" style="color:whitesmoke ;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">EDITAR PRODUCTO</h2>

@*@using (Html.BeginForm("Edit", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color:whitesmoke ;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Datos del Producto</h4>
        <div>
            @Html.ActionLink("Lista de Productos", "Index", null, new { @class = "btn btn-warning asd" })
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idProducto, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.TextBox("idProducto", Model.idProducto, new { @readonly = "readonly", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCategoria, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.DropDownList("idCategoria", (SelectList)ViewBag.categorias, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_prod, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pre_prod, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pre_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pre_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sto_prod, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sto_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sto_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img_prod, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.des_prod, htmlAttributes: new { @class = "control-label col-md-2 asd" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.des_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.des_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-success" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}
</body>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    .asd{
        color:whitesmoke
    }
</style>

Proyecto_DSW1/Views/Producto/Index.cshtml
@model IEnumerable<Proyecto_DSW1.Models.Producto>

@{
    ViewBag.Title = "MANTENIMIENTO PRODUCTO";
}
<body  style="background-color: #42413D" >

    <h2 class="text-center" style="color:whitesmoke ;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">MANTENIMIENTO DE PRODUCTOS</h2>

<p>
    @Html.ActionLink("AGREGAR PRODUCTO", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table" style="background-color: #42413D; border-radius: 10px ">
    <tr>
        <th>
            CODIGO
        </th>
        <th>
            CATEGORIA
        </th>
        <th>
            NOMBRE
        </th>
        <th>
            PRECIO
        </th>
        <th>
            STOCK
        </th>

        <th>
            IMAGEN
        </th>
        <th>
            MODIFICAR
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.nom_cat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nom_prod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pre_prod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sto_prod)
            </td>
            <td>
                <img class="container-img" src="@Url.Content(item.img_prod)" alt="Photo" style="width:120px;height:70px" />
            </td>
            <td>
                @Html.ActionLink("MODIFICAR", "Edit", new { id = item.idProducto }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("ELIMINAR", "Delete", new { id = item.idProducto }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>
<br />
</body>

<style>

    .container-img {
        width: 120px;
        height: 70px;
        border-radius:10px;
    }

.container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
    th {
        text-align: center;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        color: whitesmoke;
    }

    td {
        text-align: center;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        color: whitesmoke;
    }

    .texto {
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif
    }
</style>

Proyecto_DSW1/Views/Producto/IndexCarrito.cshtml
@model IEnumerable<Proyecto_DSW1.Models.Producto>

@{
    ViewBag.Tittle = "Index";
}
<body style="background-color: #42413D">

    <h2 class="text-center" style="font-size:100px ;color:whitesmoke ;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">STORE</h2>
    <!-- SLIDER -->
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="banner-img" src="~/fotos/bannerLG.png" alt="...">
            </div>
            <div class="item">
                <img class="banner-img" src="~/fotos/bannerLaptop.jpg" alt="...">
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container container-productos">
        @foreach (var item in Model)
        {
            <div class="producto-item">
                <div class="product-inner">
                    <div class="product-thumb has-back-image">
                        <img src="@Url.Content( item.img_prod)" alt="@item.des_prod" />
                        <div class="gorup-button">
                            <a href="detail-prod.html" class="quick-view"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    <div class="product-info">
                        <p class="text-uppercase marca">@item.Categoria.nom_cat</p>
                        <h3 class="product-name">@item.nom_prod</h3>
                        <span class="price" style="font-weight: 600">@String.Format("{0:C}", item.pre_prod)</span>
                        <p class="price-normal">Stock: @item.sto_prod</p>
                        <div class="button">
                            @Html.ActionLink("Agregar al carrito", "AgregarCarrito", "Carrito", new { id = item.idProducto }, "")
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @section Scripts
{
        <script>
     $(function () {
         $(".agregar").on("click", function (event) {
             event.preventDefault();
             var idProducto = $(this).parent().parent().find("h5:eq(0)").text();
             var cantidad = $(this).parent().parent().find("input").val();

             $.ajax(
                 {
                     url: "@Url.Action("AgregarCarrito", "Carrito")",
                     data: { id: idProducto, cantidad: cantidad },
                     type: "post",
                     success: function (response) {
                         window.location.href = "@Url.Action("AgregarCarrito", "Carrito")";
                     },
                     error: function (err, error) {
                         alert(error + " " + idProducto + " " + cantidad);
                     }
                 }
             );
         });

         $(".numbers").keydown(function (e) {

             if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 40]) !== -1 ||
                 (e.keyCode == 65 && e.ctrlKey === true) ||
                 (e.keyCode >= 35 && e.keyCode <= 39)) {
                 return;
             }

             if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                 e.preventDefault();
             }
         });

     });
        </script>
    }
</body>
<style>
    .banner-img {
        width: 100%;
        height: 100%;
    }
    img {
        max-width: 200px;
        max-height: 200px;
        vertical-align: middle;
    }

    .button {
        color: #fff;
        cursor: pointer;
        display: inline-block;
        padding: 9px 25px;
        text-align: center;
        text-transform: uppercase;
        -webkit-transition: all 0.3s ease 0s;
        -o-transition: all 0.3s ease 0s;
        transition: all 0.3s ease 0s;
        background: transparent;
        position: relative;
        background-color: #111111;
        font-size: 12px;
        border: none;
    }

        .button:hover,
        input[type="submit"]:hover {
            background-color: #e5e5e5;
            color: #000;
        }

    /*Producto*/
    .container-productos {
        overflow:hidden;
    }
    .producto-item{
        display:inline-block;
        float:left;
    }
    .product-inner {
        margin: 10px;
        border: 2px solid black;
        border-radius: 15px;
    }

    .product-inner .product-thumb {
            position: relative;
        }

    .product-inner .product-info {
            text-align: left;
        }

    .product-inner .product-name {
            margin-bottom: 8px;
            /*	margin-top: 5px;*/
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    th {
        text-align: center;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        color: whitesmoke;
    }

    td {
        text-align: center;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        color: whitesmoke;
    }

    .texto {
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif
    }
</style>